# Fill in these constants and rename the file to secrets.py

TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""
TWITTER_ACCOUNT_TO_FOLLOW = ""

DISCORD_TOKEN = ""
DISCORD_CHANNEL_ID = 0  # insert int ID
